#!/usr/bin/env node

const fs = require('fs'),
	conventionalCommitMessageRegExp = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)/g,
	commitMsgFile = process.argv[2]
	message = fs.readFileSync(commitMsgFile, 'utf8'),
	isValid = conventionalCommitMessageRegExp.test(message);
let exitCode = 0;

if(!isValid) {
	console.log('Cannot commit: the commit message does not comply with conventional commits standards.');
	exitCode = 1;
}

process.exit(exitCode);