#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

fs.readFile(path.join(__dirname, '..', 'example', 'index.ts'), 'utf8', (err, data) => {
  if (err) {
    console.error(err);
    return;
  }

  const lines = data.split('\n');
  const regex = /^[a-f0-9]{64}$/gm;

  lines.forEach((line) => {
    const match = regex.exec(line);
    if (match) {
      const token = match[1];
      console.log('Match found in line:', line);
      console.log('Token:', token);
      process.exit(1);
    }
  });
});
